### ISSUE TITLE
memes-api MemeSource init failed!

### ISSUE THREAD

**Issue by copurxia** [lgc2333/koishi-plugin-memes-api#3]
```web-idl
2023-07-13 12:50:28 [E] memes-api MemeSource init failed!
2023-07-13 12:50:28 [E] memes-api MemeError: unexpected-error (AxiosError: timeout of 1000ms exceeded)
                            at MemeSource.request (/koishi/node_modules/koishi-plugin-memes-api/lib/data-source.js:79:19)
                            at runNextTicks (node:internal/process/task_queues:60:5)
                            at listOnTimeout (node:internal/timers:538:9)
                            at process.processTimers (node:internal/timers:512:7)
                            at async MemeSource.renderList (/koishi/node_modules/koishi-plugin-memes-api/lib/data-source.js:86:39)
                            at async MemeSource.initMemeList (/koishi/node_modules/koishi-plugin-memes-api/lib/data-source.js:43:9)
                            at async MemeSource.init (/koishi/node_modules/koishi-plugin-memes-api/lib/data-source.js:31:9)
                            at async Object.apply (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:37:9)
```
用的镜像是`geyinchi/meme-generator:latest`（官方镜像也没成）
请求设置只动了endpoint的ip

**Comment by copurxia** [comment]
全局设置代理的时候，把全局的代理设置复制进来就好了
