### ISSUE TITLE
meme ls的时候会让gocq出现无法发图片的情况

### ISSUE THREAD

**Issue by xixi-furry** [lgc2333/koishi-plugin-memes-api#6]
具体提示是:

**koishi错误**：
```
session Error: Error with request send_group_msg, args: {"group_id":"721226575","message":[{"type":"text","data":{"text":"触发方式：“关键词 + 图片/文字”\n发送 “表情详情 + 关键词” 查看表情参数和预览\n目前支持的表情列表："}},{"type":"image","data":{"file":"data:image/.jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAe9BmYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5...
                            at _Internal._get (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:118:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:149:20)
                            at async _OneBotMessageEncoder.flush (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:733:159)
                            at async _OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:450:5)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2293:7
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2155:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:881:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:881:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:881:16)
```

**GoCQHTTP报错**
```
CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD/2Q==,cache=0] 到MiraiGo Element时出现错误: invalid image. 
[2023-08-14 00:32:25] [WARNING]: 群消息发送失败: 账号可能被风控. 
```

个人猜测可能跟图片转换有关系（？）感觉是ls太大了就炸了。建议可以改成直接输出主仓库内的md文档？

**Comment by lgc2333** [comment]
mime文件头问题，这里出现的是`image/.jpeg`，正常应该没有`.`，应该是我的问题，晚点修

**Comment by lgc2333** [comment]
fixed in https://github.com/lgc2333/koishi-plugin-memes-api/commit/d8fce417d11007fcd6b60ffba65f0b9ad4b5caaa
maybe

**Comment by xixi-furry** [comment]
测试正常，over
